### ISSUE TITLE
heketi-storage.json is missing

### ISSUE THREAD

**Issue by akuryan** [psyhomb/heketi#2]
Your guide is awesome, but it is missing `heketi-storage.json` file

**Comment by psyhomb** [comment]
Hey @akuryan glad you find it usable!

If everything's configured correctly `heketi-storage.json` will be generated after executing `heketi-cli setup-openshift-heketi-storage` command, see [README.md](https://github.com/psyhomb/heketi#heketi-db).

**Comment by akuryan** [comment]
Aha, my bad - misunderstood that it shall be generated by this command
